version: '3.8'

services:
  agentoz:
    image: ${DOCKER_IMAGE}
    container_name: agentoz
    restart: always
    ports:
      - "8003:8003"
      - "20883:20883"
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SERVICE_IP=${SERVICE_IP}
    networks:
      - deepknow-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  deepknow-network:
    external: true
